version: '3'

services:
  app:
    container_name: whatsapp-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ribeirovisk/whatsapp-api:1.1
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3000
      # Adicione as configurações necessárias para a conexão com o RabbitMQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ribeirovisk
      - RABBITMQ_PASSWORD=Hce@123
    ports:
      - "3000:3000"
    cap_add:
      - SYS_ADMIN

  rabbitmq:
    image: "rabbitmq:3.13.0-management-alpine"
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=ribeirovisk
      - RABBITMQ_DEFAULT_PASS=Hce@123
    ports:
      - "5672:5672"
      - "15672:15672"
